### ISSUE TITLE
微博模拟登录

### ISSUE THREAD

**Issue by XueSeason** [XueSeason/Hacker#3]
开启 Charles，打开 Chrome 登录微博，登录成后，抓取所有可能到包。

搜索你的**密码**，发现并没有任何一个请求有发送微博密码，同时搜索**账号**信息，没有任何可用的结果。

可以猜想，发送的账号和密码可能被**加密**了。

此时可以搜索 `username` 关键字，查找这些字段被加密的地方。此时找到一个 `i.sso.sina.com.cn/js/ssologin.js` 文件，分析代码可以找到以下几个函数和关键代码：

```javascript
loginByXMLHttpRequest(username, password, savestate, qrcode_flag)
loginByIframe(username, password, savestate, qrcode_flag)
loginByScript(username, password, savestate, qrcode_flag)

// prelogin 方法下
username = sinaSSOEncoder.base64.encode(urlencode(username))
```

可以猜想 `username` 被转成了 `bese64`，通过微博账号在控制台输入：

```javascript
btoa(encodeURIComponent('xxxxx@qq.com'))
```

即可得到微博账号的一串 `base64` 字符串，然后在 Charles 中继续搜索改字符串。

发现在 GET `https://login.sina.com.cn/sso/prelogin.php` 和 POST `https://login.sina.com.cn/sso/login.php` 时，分别在 QueryString 和 Form 表单中的 `su` 字段，带上了这串处理后的字符串。由此可见 `su` 就是我们的账号。

我们先从 prelogin 入手，我们细心地将相关代码提取出来：

```javascript
// 调用 prelogin 代码
me.prelogin({
  username: username
}, callback)

// objMerge 合并对象 kv
var objMerge = function(obj1, obj2) {
  for (var item in obj2) {
    obj1[item] = obj2[item]
  }
  return obj1
};

// 生成 URL，简单点理解就是将对象拼接成 QueryString
var makeURL = function(url, request) {
  return url + urlAndChar(url) + httpBuildQuery(request)
};
var urlAndChar = function(url) {
  return (/\?/.test(url) ? "&" : "?")
};
var httpBuildQuery = function(obj) {
  if (typeof obj != "object") {
    return ""
  }
  var arr = new Array();
  for (var key in obj) {
    if (typeof obj[key] == "function") {
      continue
    }
    arr.push(key + "=" + urlencode(obj[key]))
  }
  return arr.join("&")
};

// 插入一段 JS 代码到 script 标签并执行
var excuteScript = function(id, scriptSource, charset) {
  removeNode(id);
  var head = document.getElementsByTagName("head")[0];
  var newScript = document.createElement("script");
  newScript.charset = charset || "gb2312";
  newScript.id = id;
  newScript.type = "text/javascript";
  newScript.src = makeURL(scriptSource, {
    client: me.getClientType(),
    _: (new Date()).getTime()
  });
  head.appendChild(newScript)
};

// 获取客户端类型，该脚本会固定输出 ssologin.js(v1.4.19)
this.getClientType = function() {
  return me.getVersion().split(" ")[0]
};
this.getVersion = function() {
  return "ssologin.js(v1.4.19) 2017-01-09"
};

// prelogin 内部逻辑
this.prelogin = function(config, callback) {
  var url = ssoPreLoginUrl;
  var username = config.username || "";
  // base64 处理账号
  username = sinaSSOEncoder.base64.encode(urlencode(username));
  delete config.username;
  var arrQuery = {
    entry: me.entry, // 追踪到最后，发现是一个固定的 weibo 值
    callback: me.name + ".preloginCallBack", // JSONP 相关的调用方式
    su: username, // base64 处理后的 username
    rsakt: "mod"
  };
  // 拼接 URL
  url = makeURL(url, objMerge(arrQuery, config));
  // JSONP 的回调
  me.preloginCallBack = function(result) {
    if (result && result.retcode == 0) {
      me.setServerTime(result.servertime);
      me.nonce = result.nonce;
      me.rsaPubkey = result.pubkey;
      me.rsakv = result.rsakv;
      pcid = result.pcid;
      preloginTime = (new Date()).getTime() - preloginTimeStart - (parseInt(result.exectime, 10) || 0)
    }
    if (typeof callback == "function") {
      callback(result)
    }
  };
  preloginTimeStart = (new Date()).getTime();
  excuteScript(me.scriptId, url)
};
```

可以看出 **preLogin** 主要是带参数请求获得一段 JSON 参数。

QueryString 主要有以下参数：

- entry: weibo
- callback: sinaSSOController.preloginCallBack
- su: base64 处理后的账号
- rsakt: mod
- client: ssologin.js(v1.4.19)
- _: 当前时间戳 (new Date()).getTime()

继续分析请求 login.php 对应着抓包来的 form 表单，分析 ssologin.js 代码，可以知道这个 form 是如何生成的：

```yaml
# 基本固定参数
entry: 'weibo'
gateway: '1'
from: ''
savestate: '7'
useticket: '1'
pagerefer: ''
vsnf: '1'
su: username
service: 'miniblog'
pwencode: rsa2
sr: 1920*1080
encoding: UTF-8
# preloginTime 随便填一个数字就好了
prelt: 53

# 根据 showpin 参数确认是否输入验证码
door: 验证码

# prelogin 回复的值
nonce: S79EWR
pcid: gz-c1a9643dd132af46aae0a346449b00fc51d1
servertime: 1489033504
rsakv: 1330428213
# 加密后的密码
sp: 2a75606599d7d16eec9cb5a0fd5d37514f83a971ac9c707e08d19873113f42599ed793d48c9acb87e3138df2e8b1f05121db67675c46f13cc55b630c093f1675c45de263946259a3cd6953d683aacccb9b1cd3ce9eebdc533b8b299371fd7c291848cfeb95f3a7dd1accbd81f57a5fd33f1803d3472b451abbb1f9d9915daed2

url: http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOController.feedBackUrlCallBack
```

以下是 password 的加密过程：

```javascript
var makeRequest = function(username, password, savestate, qrcode_flag) {
  ...
  if ((me.loginType & rsa) && me.servertime && sinaSSOEncoder && sinaSSOEncoder.RSAKey) {
    request.servertime = me.servertime;
    request.nonce = me.nonce;
    request.pwencode = "rsa2";
    request.rsakv = me.rsakv;
    // 重点就是这里的一段加密过程
    var RSAKey = new sinaSSOEncoder.RSAKey();
    RSAKey.setPublic(me.rsaPubkey, "10001");
    password = RSAKey.encrypt([me.servertime, me.nonce].join("\t") + "\n" + password)
  } else {
    if ((me.loginType & wsse) && me.servertime && sinaSSOEncoder && sinaSSOEncoder.hex_sha1) {
      request.servertime = me.servertime;
      request.nonce = me.nonce;
      request.pwencode = "wsse";
      password = sinaSSOEncoder.hex_sha1("" + sinaSSOEncoder.hex_sha1(sinaSSOEncoder.hex_sha1(password)) + me.servertime + me.nonce)
    }
  }
  request.sp = password;
  ...
};
```

知道加密过程以及 form 各个参数的填写，那么现在登录请求就很好模拟了。至于验证码的，重点关注下 showpin 这个参数就好了。
